import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { WorkspaceNav } from "./workspace-nav";

/**
 * Root layout for the James Joseph Associates intelligence app.
 *
 * This file defines the HTML shell shared by every route in the Next.js app.
 *
 * It gives the frontend a stable place to configure:
 *
 * - global fonts
 * - global CSS
 * - browser metadata
 * - the root `<html>` and `<body>` structure
 *
 * In plain language:
 *
 * - this file answers the question:
 *
 *     "What wraps every page in the website?"
 *
 * - it does not render page-specific content
 * - it does not fetch backend data
 * - it does not connect to Supabase
 * - it does not call LangChain or LangGraph
 * - it should stay focused on application-wide page setup
 *
 * Notes
 * -----
 * - App Router layouts wrap their child routes.
 * - The `children` prop is where the active page is rendered.
 * - Global CSS is imported here so it applies across the whole frontend.
 */

// Browser and search metadata for the app.
//   - This replaces the default Create Next App text.
//   - It affects the page title and description generated by Next.js.
export const metadata: Metadata = {
  title: "James Joseph Associates Intelligence",
  description:
    "Recruitment intelligence workspace for candidate context, job matching, and controlled workflow actions.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /**
   * Render the application-wide document shell.
   *
   * Parameters
   * ----------
   * children : React.ReactNode
   *   The active page or nested layout rendered by the App Router.
   *
   * Notes
   * -----
   * - This component is shared by every page.
   * - The `<html>` element sets the language and font CSS variables.
   * - The `<body>` element provides a full-height flex container so pages can
   *   fill the viewport cleanly.
   *
   * In plain language:
   *
   * - load the global page frame
   * - apply the fonts
   * - render the current page inside the body
   */

  return (
    <html lang="en" className="h-full antialiased">
      {/* 
        Shared body wrapper.
        - `min-h-full` lets pages fill the available browser height.
        - `flex flex-col` gives page layouts a stable vertical structure.
      */}
      <body className="min-h-full flex flex-col">
        <ClerkProvider afterSignOutUrl="/sign-in">
          <WorkspaceNav />
          <div className="flex-1">{children}</div>
        </ClerkProvider>
      </body>
    </html>
  );
}
