"""
Common API response schemas for the James Joseph Associates intelligence API.

This module contains Pydantic models that are shared across API endpoint groups.

It gives the rest of the repository a stable way to talk about:

- small API response shapes
- response validation
- OpenAI documentation generated by FastAPI
- schemas that are not tied to one recruitment-domain area

Keeping common schemas in one place makes the project easier to understand
because:

- `backend.api.v1.health` can focus on the health endpoint itself
- endpoint modules can share small response models without duplicating them
- tests can verify response shapes using the same models as the API
- future API contract work has a clear home for cross-cutting schemas

In plain language:

- this module answers the question:

    "What small response shapes are shared by the API?"

- it does not define database tables
- it does not define recruitment-domain entities
- it does not contain route handlers or business logic

Notes
-----
- These are Pydantic models, not Supabase table definitions.
- Pydantic models describe and validate Python data at the API boundary.
- FastPAI uses these models to validate responses and generate OpenAPI docs.
- Domain-specific schemas should live in their own files later, for example:

    - `backend.schemas.ingestion`
    - `backend.schemas.entities`
    - `backend.schemas.documents`
    - `backend.schemas.matching`

Current schemas
---------------
This module currently defines:

    HealthResponse

which is returned by:

    GET /api/v1/health
"""

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

class HealthResponse(BaseModel):
    """
    Response returned by the lightweight API health endpoint.

    Attributes
    ----------
    status : Literal["ok"]
        Liveness status for the API application.

        The value is currently fixed to `"ok"` because this endpoint only proves
        that the FastAPI app and route registration are working.

    service : str
        Stable service identifier for the backend API.

        This is useful in logs, tests, deployment checks, and future monitoring.

    version : str
        Backend API version string.

        During early Phase 1 this should match the FastAPI application version.

    Notes
    -----
    - This is a shallow liveness response.
    - It does not prove that Supabase is reachable.
    - It does not prove that model providers are reachable.
    - It does not prove that Make.com workflows are configured.

    In plain language:

    - if this model is returned successfully, the Python API is alive
    - deeper system checks should be added later as separate readiness endpoints

    Example
    -------
    A successful health response should look like:

        {
            "status": "ok",
            "service": "james-joseph-associates-api",
            "version": "0.1.0"
        }
    """

    # Reject unexpected fields so API responses stay strict
    #   - Without this, accidental extra keys could appear in responses and still
    #     pass validation.
    #   - For a small health response that is meant to be a stable deployment check,
    #     a strict schema is clearer and easier to test.
    model_config = ConfigDict(extra="forbid")

    # `status` is intentionally fixed to "ok"
    #   - This endpoint is a simple liveness check, not a detailed status report.
    #   - If we later need states such as "degraded" or "unready", they should belong
    #     to a separate readiness endpoint that checks real dependencies.
    status: Literal["ok"] = Field(
        description="Liveness status for the API application.",
    )

    # `service` identifies which backend produced the response
    #   - This is useful once multiple services, deployment, logs, or monitors exist.
    #   - It also makes the health response a little more informative than returning
    #     only {"status": "ok"}
    service: str = Field(
        min_length=1,
        description="Stable service identifier for the backend API.",
    )

    # `version` gives deployment checks and tests a simple way to confirm which API is
    # currently responding
    #   - This is not a substitute for full release metadata, but it is enough for the
    #     first backend foundation slice.
    version: str = Field(
        min_length=1,
        description="Current backend API version string.",
    )

__all__ = ["HealthResponse"]